image: alpine:edge

# The mr-settings check needs to run in a MR specific context. With this block,
# the whole pipeline runs in that context for MRs. Otherwise we would have two
# pipelines for MRs.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'wip'

before_script: &global_before_scripts
  - ".ci/note.sh"
  - apk upgrade -U
  - "adduser -D build"

stages:
  - test

pytest:
  stage: test
  script:
    - "apk -q add git"
    - "su build -c 'git config --global user.email ci@ci'"
    - "su build -c 'git config --global user.name CI'"
    - "echo 'build ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
    - ".ci/pytest.sh"
  after_script:
    - "cp /home/build/.local/var/pmbootstrap/log_testsuite.txt ."
  artifacts:
    when: on_failure
    paths:
      - "log_testsuite.txt"

